//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

type LevelData struct {
	Name  string
	Value int
	Color string
}

func main() {
	levels := []LevelData{
		{"Critical", 10, "ANSI_PURPLE_BACKGROUND + ANSI_WHITE"},
		{"Error", 20, "ANSI_RED_BACKGROUND + ANSI_WHITE"},
		{"Warn", 30, "ANSI_YELLOW_BACKGROUND + ANSI_BLACK"},
		{"Info", 50, "ANSI_BLUE_BACKGROUND + ANSI_WHITE"},
		{"Debug", 70, "ANSI_RED_BACKGROUND + ANSI_WHITE"},
		{"Verbose", 100, `""`},
	}

	var buf bytes.Buffer

	buf.WriteString(`// Code generated by generate.go. DO NOT EDIT.

package log

import "fmt"

// Config represents the config for all LogLevels
type Config struct {
`)
	for _, l := range levels {
		buf.WriteString(fmt.Sprintf("\t%s LevelConfig\n", l.Name))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("const (\n\tNONE LogLevel = 0\n")
	for _, l := range levels {
		buf.WriteString(fmt.Sprintf("\t%s LogLevel = %d\n", strings.ToUpper(l.Name), l.Value))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("var level = map[string]LogLevel{\n\t\"NONE\": NONE,\n")
	for _, l := range levels {
		upper := strings.ToUpper(l.Name)
		buf.WriteString(fmt.Sprintf("\t\"%s\": %s,\n", upper, upper))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var lvlColor = map[LogLevel]string{\n\tNONE: \"\",\n")
	for _, l := range levels {
		upper := strings.ToUpper(l.Name)
		buf.WriteString(fmt.Sprintf("\t%s: %s,\n", upper, l.Color))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("func getConfigForLevel(level LogLevel) LevelConfig {\n\tswitch level {\n")

	for _, l := range levels {
		upper := strings.ToUpper(l.Name)
		buf.WriteString(fmt.Sprintf("\tcase %s:\n\t\treturn config.%s\n", upper, l.Name))
	}

	buf.WriteString(`	default:
		return config.Info
	}
}

func applyShowCaller(config *Config, show bool) {
`)

	for _, l := range levels {
		buf.WriteString(fmt.Sprintf("\tsetCallerForLevel(&config.%s, show)\n", l.Name))
	}
	buf.WriteString("}\n\n")

	for _, l := range levels {
		upper := strings.ToUpper(l.Name)
		buf.WriteString(fmt.Sprintf(`// %[1]s logs a message at the %[2]s level
func %[1]s(params ...interface{}) {
	print(%[2]s, params...)
}

// %[1]sf logs a formatted message at the %[2]s level
func %[1]sf(format string, params ...interface{}) {
	print(%[2]s, fmt.Sprintf(format, params...))
}

// %[1]sfln logs a formatted message at the %[2]s level with an appended newline
func %[1]sfln(format string, params ...interface{}) {
	println(%[2]s, fmt.Sprintf(format, params...))
}

// %[1]sln logs a message at the %[2]s level with an appended newline
func %[1]sln(params ...interface{}) {
	println(%[2]s, params...)
}

`, l.Name, upper))
	}

	b, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println("Error formatting source:", err)
		os.Exit(1)
	}

	err = os.WriteFile("generated_levels.go", b, 0644)
	if err != nil {
		fmt.Println("Error writing file:", err)
		os.Exit(1)
	}

	fmt.Println("generated_levels.go successfully created!")
}
