// Code generated by generate.go. DO NOT EDIT.

package log

import "fmt"

// Config represents the config for all LogLevels
type Config struct {
	Critical LevelConfig
	Error    LevelConfig
	Warn     LevelConfig
	Info     LevelConfig
	Debug    LevelConfig
	Verbose  LevelConfig
}

const (
	NONE     LogLevel = 0
	CRITICAL LogLevel = 10
	ERROR    LogLevel = 20
	WARN     LogLevel = 30
	INFO     LogLevel = 50
	DEBUG    LogLevel = 70
	VERBOSE  LogLevel = 100
)

var level = map[string]LogLevel{
	"NONE":     NONE,
	"CRITICAL": CRITICAL,
	"ERROR":    ERROR,
	"WARN":     WARN,
	"INFO":     INFO,
	"DEBUG":    DEBUG,
	"VERBOSE":  VERBOSE,
}

var lvlColor = map[LogLevel]string{
	NONE:     "",
	CRITICAL: ANSI_PURPLE_BACKGROUND + ANSI_WHITE,
	ERROR:    ANSI_RED_BACKGROUND + ANSI_WHITE,
	WARN:     ANSI_YELLOW_BACKGROUND + ANSI_BLACK,
	INFO:     ANSI_BLUE_BACKGROUND + ANSI_WHITE,
	DEBUG:    ANSI_RED_BACKGROUND + ANSI_WHITE,
	VERBOSE:  "",
}

func getConfigForLevel(level LogLevel) LevelConfig {
	switch level {
	case CRITICAL:
		return config.Critical
	case ERROR:
		return config.Error
	case WARN:
		return config.Warn
	case INFO:
		return config.Info
	case DEBUG:
		return config.Debug
	case VERBOSE:
		return config.Verbose
	default:
		return config.Info
	}
}

func applyShowCaller(config *Config, show bool) {
	setCallerForLevel(&config.Critical, show)
	setCallerForLevel(&config.Error, show)
	setCallerForLevel(&config.Warn, show)
	setCallerForLevel(&config.Info, show)
	setCallerForLevel(&config.Debug, show)
	setCallerForLevel(&config.Verbose, show)
}

// Critical logs a message at the CRITICAL level
func Critical(params ...interface{}) {
	print(CRITICAL, params...)
}

// Criticalf logs a formatted message at the CRITICAL level
func Criticalf(format string, params ...interface{}) {
	print(CRITICAL, fmt.Sprintf(format, params...))
}

// Criticalln logs a message at the CRITICAL level with an appended newline
func Criticalln(params ...interface{}) {
	println(CRITICAL, params...)
}

// Error logs a message at the ERROR level
func Error(params ...interface{}) {
	print(ERROR, params...)
}

// Errorf logs a formatted message at the ERROR level
func Errorf(format string, params ...interface{}) {
	print(ERROR, fmt.Sprintf(format, params...))
}

// Errorln logs a message at the ERROR level with an appended newline
func Errorln(params ...interface{}) {
	println(ERROR, params...)
}

// Warn logs a message at the WARN level
func Warn(params ...interface{}) {
	print(WARN, params...)
}

// Warnf logs a formatted message at the WARN level
func Warnf(format string, params ...interface{}) {
	print(WARN, fmt.Sprintf(format, params...))
}

// Warnln logs a message at the WARN level with an appended newline
func Warnln(params ...interface{}) {
	println(WARN, params...)
}

// Info logs a message at the INFO level
func Info(params ...interface{}) {
	print(INFO, params...)
}

// Infof logs a formatted message at the INFO level
func Infof(format string, params ...interface{}) {
	print(INFO, fmt.Sprintf(format, params...))
}

// Infoln logs a message at the INFO level with an appended newline
func Infoln(params ...interface{}) {
	println(INFO, params...)
}

// Debug logs a message at the DEBUG level
func Debug(params ...interface{}) {
	print(DEBUG, params...)
}

// Debugf logs a formatted message at the DEBUG level
func Debugf(format string, params ...interface{}) {
	print(DEBUG, fmt.Sprintf(format, params...))
}

// Debugln logs a message at the DEBUG level with an appended newline
func Debugln(params ...interface{}) {
	println(DEBUG, params...)
}

// Verbose logs a message at the VERBOSE level
func Verbose(params ...interface{}) {
	print(VERBOSE, params...)
}

// Verbosef logs a formatted message at the VERBOSE level
func Verbosef(format string, params ...interface{}) {
	print(VERBOSE, fmt.Sprintf(format, params...))
}

// Verboseln logs a message at the VERBOSE level with an appended newline
func Verboseln(params ...interface{}) {
	println(VERBOSE, params...)
}
